apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-platform-upgrade-prep
  namespace: ztp-group
spec:
  managedPolicies:
  - du-upgrade-platform-upgrade-prep
  clusters:
  - sno01
  remediationStrategy:
    maxConcurrency: 1
  enable: true