---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "ztpc156-dfw-ocp-run"
  namespace: "ztpc156-dfw-ocp-run"
spec:
  baseDomain: "dfw.ocp.run"
  pullSecretRef:
    name: "pull-secret"
  clusterImageSetNameRef: "openshift-v4.11.4"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJn0yUIqXBCIglm0UUA+qLF+Dlr5U9pneFLOFdt+f9XJ dlakshma@redhat.com"
  clusters:
  - clusterName: "ztpc156"
    networkType: "OVNKubernetes"
    clusterLabels:
      common: true
      5gcore-profile: true
      sites : "ztpc156"
    clusterNetwork:
      - cidr: "10.100.0.0/16"
        hostPrefix: 23
    machineNetwork:
      - cidr: "192.168.156.0/24"
    serviceNetwork:
      - "172.101.0.0/16"
    #additionalNTPSources:
    #  - "192.168.2.1"
    nodes:
      - hostName: "ztpc156"
        role: "master"
        bmcAddress: "idrac-virtualmedia+https://192.168.110.111/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "bmc-secret"
        bootMACAddress: "24:6e:96:59:33:e8"
        bootMode: "UEFI"
        rootDeviceHints:
          # /dev/sdb
          hctl: '1:2:0:0'
        cpuset: "0-1,38-39"
        nodeNetwork:
          interfaces:
            - name: "eno1"
              macAddress: "24:6e:96:59:33:e8"
            - name: "ens5f0"
              macAddress: "0c:42:a1:aa:95:b2"
            - name: "ens5f1"
              macAddress: "0c:42:a1:aa:95:b3"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                macAddress: "24:6e:96:59:33:e8"
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.156.111
                    prefix-length: 24
                ipv6:
                  enabled: false
              - name: ens5f0
                type: ethernet
                state: up
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
              - name: ens5f1
                type: ethernet
                state: up
                ipv4:
                  enabled: false
                ipv6:
                  enabled: false
            dns-resolver:
              config:
                search:
                - dfw.ocp.run
                server:
                - 192.168.156.10
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.156.1
                next-hop-interface: eno1
                table-id: 254
