---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "sno1"
  namespace: "sno1"
spec:
  baseDomain: "dinesh156.dfw.ocp.run"
  pullSecretRef:
    name: "pull-secret"
  clusterImageSetNameRef: "openshift-v4.11.26"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJn0yUIqXBCIglm0UUA+qLF+Dlr5U9pneFLOFdt+f9XJ dlakshma@redhat.com"
  clusters:
  - clusterName: "sno1"
    networkType: "OVNKubernetes"
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
      du-profile: "v4.11"
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
#      common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
#      group-du-sno: ""
      # ../policygentemplates/group-5gcore-ranGen.yaml will apply to all clusters with '5g-core-profile: true'
#      5gcore-profile: true
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "sno1"
    clusterNetwork:
      - cidr: "10.100.0.0/16"
        hostPrefix: 23
    machineNetwork:
      - cidr: "192.168.156.0/24"
    serviceNetwork:
      - "172.101.0.0/16"
    #additionalNTPSources:
    #  - "192.168.2.1"
    nodes:
      - hostName: "sno1"
        role: "master"
        bmcAddress: "idrac-virtualmedia+https://192.168.110.102/redfish/v1/Systems/System.Embedded.1"
        bmcCredentialsName:
          name: "bmc-secret"
        bootMACAddress: "24:6e:96:c2:95:60"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/sda"
#          wwn: "0x500a07511c860809"
#          hctl: '1:2:0:0'
        cpuset: "0-1,30-31"
        nodeNetwork:
          interfaces:
            - name: "eno1"
              macAddress: "24:6e:96:c2:95:60"
#            - name: "ens5f0"
#              macAddress: "0c:42:a1:aa:95:b2"
#            - name: "ens5f1"
#              macAddress: "0c:42:a1:aa:95:b3"
          config:
            interfaces:
              - name: eno1
                type: ethernet
                state: up
                macAddress: "24:6e:96:c2:95:60"
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.156.102
                    prefix-length: 24
                ipv6:
                  enabled: false
#              - name: ens5f0
#                type: ethernet
#                state: up
#                ipv4:
#                  enabled: false
#                ipv6:
#                  enabled: false
#              - name: ens5f1
#                type: ethernet
#                state: up
#                ipv4:
#                  enabled: false
#                ipv6:
#                  enabled: false
            dns-resolver:
              config:
                search:
                - dinesh156.dfw.ocp.run
                server:
                - 192.168.156.10
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-address: 192.168.156.1
                next-hop-interface: eno1
                table-id: 254
