---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "group-du-sno"
  namespace: "ztp-group"
spec:
  bindingRules:
    group-du-sno: ""
    du-profile: "v4.11"
  mcp: "master"
  sourceFiles:
    # This will disable the console GUI
#    - fileName: ConsoleOperatorDisable.yaml
#      policyName: "config-policy"
#    # Set Local Storage Config
#    - fileName: StorageLV.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "dev-sdb"
#      spec:
#        storageClassDevices:
#          - storageClassName: "local-storage"
#            volumeMode: Filesystem
#            fsType: ext4
#            devicePaths:
#              - /dev/sdb
#    - fileName: StorageLV.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "dev-sdc"
#      spec:
#        storageClassDevices:
#          - storageClassName: "local-storage"
#            volumeMode: Filesystem
#            fsType: ext4
#            devicePaths:
#              - /dev/sdc
#    - fileName: StorageLV.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "dev-sdd"
#      spec:
#        storageClassDevices:
#          - storageClassName: "local-storage"
#            volumeMode: Filesystem
#            fsType: ext4
#            devicePaths:
#              - /dev/sdd
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      metadata:
        name: openshift-node-performance-profile
      spec:
        additionalKernelArgs:
        - "idle=poll"
        - "rcupdate.rcu_normal_after_boot=0"
#        - pci=realloc
        cpu:
          isolated: "2-19,22-39"
          reserved: "0-1,20-21"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
              node: 0
        nodeSelector:
          node-role.kubernetes.io/master: ''
#        globallyDisableIrqLoadBalancing: false
#sourceFiles:
    - fileName: PtpConfigSlave.yaml   # Change to PtpConfigSlaveCvl.yaml for ColumbiaVille NIC
      policyName: "config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
        - name: "slave"
          # This interface must match the hardware in this group
          interface: "ens5f0"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
#sourceFiles for sr-iov operatorconfig
#    - fileName: SriovOperatorConfig.yaml   
#      policyName: "config-policy"
#      metadata:
#        name: sriov-operator-config
#        namespace: openshift-sriov-network-operator
#      spec:
#        configDaemonNodeSelector:
#          node-role.kubernetes.io/master: ""
#        disableDrain: true
#        enableInjector: true
#        enableOperatorWebhook: true
#sourceFiles for sr-iov Network Fronthaul
#    - fileName: SriovNetwork.yaml   
#      policyName: "config-policy"
#      metadata:
#        name: sriov-nw-du-fh
#        namespace: openshift-sriov-network-operator
#      spec:
#        networkNamespace: openshift-sriov-network-operator
#  ipam: ""
#  vlan: 1000
#        resourceName: du_fh
#sourceFiles for sr-iov Network BackHaul
#    - fileName: SriovNetwork.yaml   
#      policyName: "config-policy"
#      metadata:
#       name: sriov-nw-du-bh
#        namespace: openshift-sriov-network-operator
#      spec:
#        networkNamespace: openshift-sriov-network-operator
#  ipam: ""
#  vlan: 1001
#        resourceName: du_bh