---
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "sno2"
  namespace: "ztp-site"
spec:
  bindingRules:
    sites: "sno2"
    du-profile: "v4.11"
  mcp: "master"
  sourceFiles:
# subscription policy
    - fileName: PtpSubscription.yaml
      policyName: "subscriptions-policy"
    - fileName: PtpSubscriptionNS.yaml
      policyName: "subscriptions-policy"
    - fileName: PtpSubscriptionOperGroup.yaml
      policyName: "subscriptions-policy"
    - fileName: PtpOperatorStatus.yaml
      policyName: "subscriptions-policy"
# config-policy files
    - fileName: ReduceMonitoringFootprint.yaml
      policyName: "config-policy"
    - fileName: PerformanceProfile.yaml
      policyName: "config-policy"
      metadata:
        name: openshift-node-performance-profile
      spec:
        additionalKernelArgs:
        - "idle=poll"
        - "rcupdate.rcu_normal_after_boot=0"
#        - pci=realloc
        cpu:
          # Dell Gen9 servers
          #isolated: "2-19,22-39"
          #reserved: "0-1,20-21"
          
          # Dell Gen8 servers
          isolated: "2-14,17-31"
          reserved: "0-1,15-16"
        hugepages:
          defaultHugepagesSize: 1G
          pages:
            - size: 1G
              count: 32
              node: 0
        nodeSelector:
          node-role.kubernetes.io/master: ''
#        globallyDisableIrqLoadBalancing: false
#sourceFiles:
    - fileName: PtpConfigSlave.yaml   # Change to PtpConfigSlaveCvl.yaml for ColumbiaVille NIC
      policyName: "config-policy"
      metadata:
        name: "du-ptp-slave"
      spec:
        profile:
        - name: "slave"
          # This interface must match the hardware in this group
          interface: "eno1"
          ptp4lOpts: "-2 -s --summary_interval -4"
          phc2sysOpts: "-a -r -n 24"
