apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "sno3"
  namespace: "ztp-site"
spec:
  bindingRules:
    sites: "sno3"
  mcp: "master"
  sourceFiles:
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-vf-admin"
      spec:
        deviceType: netdevice
        isRdma: true
        nicSelector:
          vendor: "15b3"
          deviceID: "1015"
          pfNames: ["ens5f0#0-0"]
        numVfs: 16
        resourceName: vfadmin
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-du-fh"
      spec:
        deviceType: netdevice
        isRdma: true
        nicSelector:
          vendor: "15b3"
          deviceID: "1015"
          pfNames: ["ens5f0#1-8"]
        numVfs: 16
        resourceName: du_fh
    - fileName: SriovNetworkNodePolicy.yaml
      policyName: "config-policy"
      metadata:
        name: "sriov-nnp-du-bh"
      spec:
        deviceType: netdevice
        isRdma: true
        nicSelector:
          vendor: "15b3"
          deviceID: "1015"
          pfNames: ["ens5f0#9-15"]
        numVfs: 16
        resourceName: du_bh
#    - fileName: SriovNetworkNodePolicy.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "policy-mt27710-0-netdevice"
#      spec:
#        deviceType: netdevice
#        isRdma: false
#        nicSelector:
#          pfNames: ["ens5f0#5-8"]
#        numVfs: 9
#        resourceName: mt27710_0_netdevice
#    - fileName: SriovNetworkNodePolicy.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "policy-mt27710-1-openshift"
#      spec:
#        deviceType: netdevice
#        isRdma: false
#        nicSelector:
#          pfNames: ["ens5f1#0-0"]
#        numVfs: 9
#        resourceName: mt27710_1_openshift
#    - fileName: SriovNetworkNodePolicy.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "policy-mt27710-1-vfio-pci"
#      spec:
#        deviceType: vfio-pci
#        isRdma: false
#        nicSelector:
#          pfNames: ["ens5f1#1-4"]
#        numVfs: 9
#        resourceName: mt27710_1_vfio_pci
#    - fileName: SriovNetworkNodePolicy.yaml
#      policyName: "config-policy"
#      metadata:
#        name: "policy-mt27710-1-netdevice"
#      spec:
#        deviceType: netdevice
#        isRdma: false
#        nicSelector:
#          pfNames: ["ens5f1#5-8"]
#        numVfs: 9
#        resourceName: mt27710_1_netdevice
